# Generated by Django 4.1.3 on 2022-11-13 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='habits',
            field=models.ManyToManyField(to='habits.habits'),
        ),
    ]
