# Generated by Django 4.1.3 on 2022-11-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_habits'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reminder_time',
            field=models.TimeField(null=True),
        ),
    ]
