# Generated by Django 4.1.3 on 2023-01-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_reminder_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reminder_time',
            field=models.IntegerField(null=True),
        ),
    ]
