# Generated by Django 4.1.3 on 2022-11-11 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('check_in_1', models.IntegerField()),
                ('check_in_2', models.IntegerField()),
                ('check_in_3', models.IntegerField()),
                ('check_in_4', models.IntegerField()),
                ('check_in_5', models.IntegerField()),
                ('check_in_6', models.IntegerField()),
                ('check_in_7', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
