# Generated by Django 4.1.3 on 2023-01-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
