# Generated by Django 4.1.3 on 2022-11-13 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit_frequency', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitfrequency',
            old_name='user_id',
            new_name='user',
        ),
    ]
