# Generated by Django 4.1.3 on 2023-01-19 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit_frequency', '0002_rename_user_id_habitfrequency_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitfrequency',
            old_name='date',
            new_name='date_submitted',
        ),
    ]
